#!/bin/bash

set -e

echo -e "\033[1;34m>>> [${0}] Starting build phase\033[0m"
( cd "$(dirname "$0")/004-matrix-mul" && make all )

echo -e "\033[1;34m>>> [${0}] Starting run phase\033[0m"
"$(dirname "$0")"/004-matrix-mul/matrix_mul_dpc
