#!/bin/bash
#
# This is a simple test to verify that the compiler has the necessary
# runtime dependencies, e.g. intel-ocloc and libsycl-dev.
#

set -e

echo -e "\033[1;34m>>> [${0}] Starting build phase\033[0m"
dpclang++ -fsycl -fsycl-targets=spir64_gen,spir64 -Xs "-device bmg" "$(dirname "$0")/006-runtime-deps/a.cpp"
