src/build/install/bin/llvm-* usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/append-file usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/bugpoint usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/diagtool usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/dsymutil usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/file-table-tform usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/llc usr/lib/llvm-dpcpp-20/bin/
src/build/install/bin/lli usr/lib/llvm-dpcpp-20/bin/

